import './globals.css'
import Theme from '../styles/theme';


export const metadata = {
  title: 'Starter Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <>
      <html lang="en">
        <Theme>
          <body>
            {children}
          </body>
        </Theme>
      </html>
    </>
  )
}
