import './globals.css'
import Theme from '../styles/theme';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <>
      <html lang="en">
        <Theme>
          <body className='pace-running pace-running'>
            <div className="pace-active">
              <div
                className="pace-progress"
              >
                <div className="pace-progress-inner" />
              </div>
              <div className="pace-activity" />
            </div>
            {children}
          </body>
        </Theme>
      </html>
    </>
  )
}
